import SideBar from "@/src/components/common/CustomSideBar";
import Header from "@/src/components/common/Header";
import { AppRoutes } from "@/src/constant/appRoutes";
import { mockQuestionData } from "@/src/data/MockData";
import Assessment from "@/src/sections/Assessment";
import { pushHandler } from "@/src/utils/genericRouting";
import useStore from "@/src/zustand-store";
// import { getQuestions } from "@/src/zustand-store/test/test.selector";
import { Box } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  // const setSelectedAns = useStore((state: any) => state.setSelectedAnswer);

  // const questions = useStore((state) => getQuestions(state, testid));

  const fetchTests = useStore((state: any) => state.fetchTests);

  // const {
  //   query: { testid, questionid },
  // } = useRouter();

  const router = useRouter();

  const getQuestionData = async () => {
    await fetchTests(router?.query?.testid);
  };

  useEffect(() => {
    getQuestionData();
  }, [router]);

  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Box
            sx={{
              backgroundColor: "#181b32",
              py: "100px",
            }}
          >
            <Header />
            <Box>
              <SideBar />
              <Assessment />
            </Box>
          </Box>
        </Box>
      </main>
    </>
  );
}
