import { Box } from "@mui/material";
import Head from "next/head";
import { useEffect, useState } from "react";
import SideBar from "../components/common/CustomSideBar";
import Header from "../components/common/Header";
import Assessment from "../components/sections/Assessment/Assessment";
import { mockQuestionData } from "../data/MockData";
import { mockDataType } from "../data/type";
import useStore from "../zustand-store";

let SelectedQueIdArray: number[] = [];
export default function Home() {
  const [queData, setQueData] = useState<mockDataType | undefined>(
    mockQuestionData[0]
  );
  const [selectedQue, setSelectedQue] = useState<number>(0);
  const [activeStep, setActiveStep] = useState(0);

  const user = useStore((state) => state.user);
  const fetchUser = useStore((state) => state.fetchUser);

  useEffect(() => {
    fetchUser();
  }, [fetchUser]);
  console.log(user);

  const handleQuestion = (data: mockDataType, index: number) => {
    console.log("getData", data);
    SelectedQueIdArray.push(index);
    setQueData(data);
    setSelectedQue(index);
  };

  const handleNext = () => {
    setActiveStep((prevActiveStep) => prevActiveStep + 5);

    setQueData(mockQuestionData[selectedQue + 1]);
    setSelectedQue(selectedQue + 1);
  };

  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Box
            sx={{
              backgroundColor: "#181b32",
              py: "100px",
            }}
          >
            <Header />
            <Box>
              <SideBar
                mockQuestionData={mockQuestionData}
                handleQuestion={handleQuestion}
                selectedQue={selectedQue}
                SelectedQueIdArray={SelectedQueIdArray}
              />
              <Assessment
                queData={queData}
                activeStep={activeStep}
                selectedQue={selectedQue}
                handleNext={handleNext}
              />
            </Box>
          </Box>
        </Box>
      </main>
    </>
  );
}
