import { Box } from "@mui/material";
import Head from "next/head";
import SideBar from "../components/common/CustomSideBar";
import Header from "../components/common/Header";
import Assessment from "../components/sections/Assessment";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Box
            sx={{
              backgroundColor: "#181b32",
              py: "100px",
            }}
          >
            <Header />
            <Box sx={{ display: "flex" }}>
              <SideBar />
              <Assessment />
            </Box>
          </Box>
        </Box>
      </main>
    </>
  );
}
